#!/usr/bin/env python

import time
import numpy as np
import roslib
import rospy
import baxter_interface

from baxter_core_msgs.msg import JointCommand

def main():
    rospy.init_node('marcelfirst')
    baxter_pub = rospy.Publisher('/robot/limb/left/joint_command', JointCommand, queue_size = 10)
    rospy.Rate(10)
    while not rospy.is_shutdown():
        jointcommand = JointCommand()
        jointcommand.mode = JointCommand.TORQUE_MODE
        jointcommand.command = [.1]
        jointcommand.names = ['left_s0']
        baxter_pub.publish(jointcommand)
if __name__ == '__main__':
    main()
